Repository avano/curly-garbanzo, pull requests merged in 2020-02, with the labels that each got.

#3 Update README.md
  README.md
Labels: help wanted

#4 Update README.md
  README.md
Labels: approved, help wanted

#6 Update README.md
  README.md
Labels: approved

#7 Update README.md
  README.md
Labels: approved

#8 Update README.md
  README.md
Labels: approved

#9 Update README.md
  README.md
Labels: approved

#10 Update README.md
  README.md
Labels: approved

#13 Update README.md
  README.md
Labels: approved, help wanted, invalid

#17 Fafram test patch 4
  .circleci/config.yml
  .travis.yml
Labels: approved
